package g2sysnet.smart_gw.models

data class DDInfo(
    val DT_DLV_SCH: String,
    val CD_DLVTIME: String,
    val FG_DLV: String,
    val FG_DLV1 : String,
    val FG_TIME: String,
    val NM_PERSON: String,
    val NO_HP: String,
    val NO_TEL: String,
    val DC_ADDRESS: String,
    val DC_ADDRESS_DETAIL: String,
    val NO_SO: String,
    val DT_SO: String,
    val TP_BIZ1: String,
    val NM_BIZ: String,
    val NM_ITEM: String,
    val NO_SN: String,
    val QT: String,
    val FG_STAIR: String,
    val TP_STAIR: String,
    val FG_EQUIP: String,
    val TP_BUILDING: String,
    val FG_LOC: String,
    val QT_WEIGHT: String,
    val AM_DLV: String,
    val AM_EQUIP: String,
    val AM_TOTAL: String,
    val NM_EMP: String,
    val DC_RMK: String,
    val CD_FIRM: String,
    val NO_SO1: String,
    val NO_LINE: String,
    val NO_LINE_DLV: String
)