package g2sysnet.smart_gw.models

data class ReceptionInfoModel (
    val NO_SO : String,
    val TP_SO : String,
    val DT_SO : String,
    val NM_EMP : String,
    val NM_PERSON : String,
    val CD_DUMMY02 : String,
    val CD_DUMMY03 : String,
    val CD_DUMMY04 : String,
    val CD_ITEM : String,
    val NM_BIZ : String,
    val NM_ITEM : String,
    val NO_SN : String,
    val NM_SYMPTOM_P : String,
    val NM_SYMPTOM : String,
    val DC_SYMPTOM : String,
    val DC_RMK : String,
    val FG_SO1 : String,
    val NM_EMP_ENGINNER : String,
    val DT_VISIT_PLAN : String,
    val CD_VISIT_TIME : String,
    val YN_AM : String,
    val AM : String,
    val AM_MATL : String,
    val AM_LABOR : String,
    val AM_VISIT : String,
    val AM_AGENCY : String,
    val YN_AM1 : String,
    val CD_FIRM : String,
    val NO_SO1 : String,
    val NO_LINE_ITEM : String,
    val NO_LINE : String,
    val CD_ITEM1 : String,
    val CD_PERSON : String
)